services:
  dj-pipelinez:
    build: .
    container_name: dj-pipelinez
    restart: unless-stopped

    runtime: nvidia
    gpus: all

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      - /mnt/leviathan/data/upscale/incoming:/watch/incoming
      - /mnt/leviathan/data/upscale/outgoing:/watch/outgoing
      - /mnt/leviathan/data/upscale/failed:/watch/failed
      - /mnt/leviathan/data/upscale/work:/watch/work
      - ./state:/state